version: '3.5'

services:
  vite:
    container_name: vite
    image: node:lts-alpine
    working_dir: /var/www/html/app
    restart: always
    volumes:
      - ./frontend/scoro-ha:/var/www/html/app
    ports:
      - "3000:3000"
    command: yarn start-dev
  lumen:
    container_name: lumen
    build: .
    entrypoint: php -S lumen:8000 -t public
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
      - /var/www/html/frontend/
